'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,Plus,X,MoveUpRight} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Switch} from '@/components/ui/switch';
import {Slider} from '@/components/ui/slider';
import {CropMarks,BrandMark} from '@/src/brand/BrandMark';
import {ResultViewer} from '@/src/result/ResultViewer';
import type {CaptureOptions,CaptureResult} from '@/server/capture/model';
import {viewportPresets} from './presets';
import {useScrollReveal} from '../motion/ScrollReveal';
type Failure={message:string;code:string;row?:number;retryable?:boolean};
const number=(n:number)=>String(n).padStart(2,'0');
function urlError(value:string){try{const u=new URL(value);if(!['https:','http:'].includes(u.protocol)||!u.hostname.includes('.'))return 'Gunakan alamat website publik.';if(u.username||u.password)return 'URL tidak boleh berisi kredensial.';return '';}catch{return 'Tambahkan URL lengkap, diawali https://.';}}
function Choice({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:{value:string;label:React.ReactNode;disabled?:boolean}[]}){return <RadioGroup className="choice-group" aria-label={label} value={value} onValueChange={onChange}>{options.map(o=><label key={o.value} style={o.disabled?{opacity:.45,cursor:"not-allowed"}:undefined} title={o.disabled?"PDF belum tersedia":undefined} className={`choice ${value===o.value?'selected':''}`}><RadioGroupItem value={o.value} disabled={o.disabled}/><span>{o.label}</span></label>)}</RadioGroup>;}
export function CaptureWorkspace(){
 useScrollReveal();
 const [mode,setMode]=useState<'single'|'batch'>('single');const [url,setUrl]=useState('');const [urls,setUrls]=useState(['','']);
 const [format,setFormat]=useState('png');const [preset,setPreset]=useState('desktop');const [width,setWidth]=useState(1920);const [height,setHeight]=useState(1080);
 const [fullPage,setFullPage]=useState(false);const [dark,setDark]=useState(false);const [delay,setDelay]=useState(1);const [scale,setScale]=useState(1);
 const [formats,setFormats]=useState(['jpeg','png','webp','pdf']);const [engineReady,setEngineReady]=useState<boolean|null>(null);
 const [state,setState]=useState<'idle'|'preparing'|'waiting'|'finalizing'|'done'|'error'>('idle');const [failure,setFailure]=useState<Failure|null>(null);const [result,setResult]=useState<CaptureResult|null>(null);const [submitted,setSubmitted]=useState(false);const [elapsed,setElapsed]=useState(0);const [batchLimit,setBatchLimit]=useState(5);
 const controller=useRef<AbortController|null>(null);const resultRef=useRef<HTMLDivElement>(null);const inputRef=useRef<HTMLInputElement>(null);const formRef=useRef<HTMLFormElement>(null);
 const busy=['preparing','waiting','finalizing'].includes(state);
 const agentState=useRef<Record<string,unknown>>({});
 useEffect(()=>{agentState.current={mode,targets:mode==='single'?[url]:urls,viewport:{preset,width,height,fullPage,scale},appearance:{darkMode:dark},output:{format},timing:{delay},status:state,result:result?{id:result.id,downloadUrl:result.downloadUrl,expiresAt:result.expiresAt}:null,error:failure};},[mode,url,urls,preset,width,height,fullPage,scale,dark,format,delay,state,result,failure]);
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'get_capture_state',title:'Baca pengaturan capture',description:'Read the current visible capture settings, status, error, and latest download link. Does not submit a capture.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input:unknown){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object');return agentState.current;}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[]);

 useEffect(()=>{fetch('/api/health').then(r=>r.json() as Promise<{batchLimit?:number;formats?:string[];providerConfigured?:boolean}>).then(x=>{if(Number.isInteger(x.batchLimit))setBatchLimit(x.batchLimit!);if(x.formats){setFormats(x.formats);setFormat(f=>x.formats!.includes(f)?f:(x.formats![0]||'png'));}setEngineReady(x.providerConfigured===true);}).catch(()=>{});return()=>controller.current?.abort();},[]);
 useEffect(()=>{if(!busy)return;const start=Date.now();const timer=setInterval(()=>setElapsed((Date.now()-start)/1000),100);return()=>clearInterval(timer);},[busy]);
 function changePreset(v:string){setPreset(v);const p=viewportPresets.find(p=>p.value===v);if(p&&p.width){setWidth(p.width);setHeight(p.height);}}
 async function submit(event?:React.FormEvent){
  event?.preventDefault();if(busy)return;setSubmitted(true);setFailure(null);setResult(null);
  const targets=(mode==='single'?[url]:urls).map(x=>x.trim());const invalid=targets.findIndex(x=>urlError(x));
  if(invalid!==-1){setFailure({code:'INVALID_URL',message:urlError(targets[invalid]),row:invalid});setState('error');formRef.current?.querySelector<HTMLInputElement>(`[data-url-row="${invalid}"]`)?.focus();return;}
  setState('preparing');setResult(null);setElapsed(0);controller.current=new AbortController();
  const options:CaptureOptions={mode,targets,viewport:{preset:preset as CaptureOptions['viewport']['preset'],width,height,fullPage,scale},appearance:{darkMode:dark},output:{format:format as CaptureOptions['output']['format']},timing:{delay}};
  if(window.innerWidth<900)resultRef.current?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});
  try{
   setState('waiting');const r=await fetch(mode==='batch'?'/api/capture/batch':'/api/capture',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(options),signal:controller.current.signal});
   setState('finalizing');const data=await r.json() as CaptureResult & Failure;if(!r.ok||!data.success){setFailure({code:data.code||'CAPTURE_FAILED',message:data.message||'Capture gagal. Silakan coba lagi.',row:data.row,retryable:data.retryable});setState('error');return;}
   setResult(data);setState('done');
  }catch(e){if(e instanceof Error&&e.name==='AbortError'){setState('idle');return;}setFailure({code:'CONNECTION_FAILED',message:'Koneksi terputus. Periksa jaringanmu lalu coba lagi.'});setState('error');}
 }
 function reset(){setResult(null);setState('idle');setFailure(null);inputRef.current?.focus();formRef.current?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});}
 const selectedCount=mode==='batch'?urls.length:1;
 return <section id="capture" className="workspace section-wrap"><div className="section-heading"><div><span className="mono section-index">002 / CAPTURE WORKSPACE</span><h2>Capture website<br/><span>sesuai kebutuhan.</span></h2></div><p>Single URL atau batch. <br/>Atur viewport, format, dan delay sebelum capture.</p></div><div className="workspace-grid"><form ref={formRef} onSubmit={submit} className="capture-form" noValidate><fieldset disabled={busy}>
 <Tabs value={mode} onValueChange={v=>{setMode(v as 'single'|'batch');setSubmitted(false);setFailure(null);if(!result)setState('idle');}} className="capture-tabs"><TabsList aria-label="Mode capture"><TabsTrigger value="single"><span>Single</span><span className="mono">01</span></TabsTrigger><TabsTrigger value="batch"><span>Batch</span><span className="mono">02—{number(batchLimit)}</span></TabsTrigger></TabsList>
 <TabsContent value="single"><label className="field-label" htmlFor="website">ALAMAT WEBSITE <span className="mono">/ URL</span></label><div className={`url-input ${submitted&&urlError(url)?'invalid':''}`}><MoveUpRight size={18}/><input id="website" ref={inputRef} data-url-row="0" type="url" inputMode="url" autoCapitalize="none" autoCorrect="off" spellCheck={false} value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://website-kamu.com" aria-invalid={submitted&&!!urlError(url)} aria-describedby="url-help"/></div><p id="url-help" className={`field-help ${submitted&&urlError(url)?'error-text':''}`}>{submitted&&urlError(url)?urlError(url):'Masukkan URL halaman publik.'}</p></TabsContent>
 <TabsContent value="batch"><div className="field-label">DAFTAR WEBSITE <span className="mono">{number(urls.length)} / {number(batchLimit)}</span></div><div className="batch-inputs">{urls.map((v,i)=><div className="batch-row-wrap" key={i}><div className={`batch-row ${submitted&&urlError(v)?'invalid':''}`}><span className="mono">{number(i+1)}</span><input data-url-row={i} aria-label={`URL ${i+1}`} aria-invalid={submitted&&!!urlError(v)} type="url" inputMode="url" autoCapitalize="none" autoCorrect="off" spellCheck={false} placeholder="https://example.com" value={v} onChange={e=>setUrls(prev=>prev.map((x,j)=>j===i?e.target.value:x))}/><button className="remove-url" type="button" aria-label={`Hapus URL ${i+1}`} disabled={urls.length===1} onClick={()=>setUrls(prev=>prev.filter((_,j)=>i!==j))}><X size={16}/></button></div>{submitted&&urlError(v)&&<p className="field-help error-text">{urlError(v)}</p>}</div>)}</div><button type="button" className="add-url" onClick={()=>setUrls([...urls,''])} disabled={urls.length>=batchLimit}><Plus size={16}/> Tambah URL</button></TabsContent></Tabs>
 <div className="control-block"><span className="field-label">FORMAT OUTPUT <span className="mono">01</span></span><Choice label="Format output" value={format} onChange={setFormat} options={[{value:'jpeg',label:'JPG'},{value:'png',label:'PNG'},{value:'webp',label:'WEBP'},{value:'pdf',label:'PDF'}].map(o=>({...o,disabled:!formats.includes(o.value)}))}/>{format==='pdf'&&<p className="field-help">Layout PDF dapat berbeda dari screenshot gambar.</p>}</div>
 <div className="control-block viewport-presets"><span className="field-label">VIEWPORT <span className="mono">02</span></span><Choice label="Preset viewport" value={preset} onChange={changePreset} options={viewportPresets.map(p=>({value:p.value,label:p.label}))}/><div className="dimensions"><label>Lebar<input aria-label="Lebar viewport" type="number" min={320} max={3840} value={width||''} onChange={e=>{setWidth(Number(e.target.value));setPreset('custom');}}/></label><span>×</span><label>Tinggi<input aria-label="Tinggi viewport" type="number" min={240} max={2160} value={height||''} onChange={e=>{setHeight(Number(e.target.value));setPreset('custom');}}/></label><span className="mono">PX</span></div></div>
 <div className="control-block area-control"><span className="field-label">AREA CAPTURE</span><Choice label="Area capture" value={fullPage?'full':'viewport'} onChange={v=>setFullPage(v==='full')} options={[{value:'viewport',label:'Viewport'},{value:'full',label:'Full page'}]}/></div>
 <div className="control-block delay-block"><label id="delay-label" className="field-label">DELAY <span className="mono">{String(delay).padStart(2,'0')} DETIK</span></label><Slider aria-labelledby="delay-label" min={0} max={10} step={1} value={[delay]} onValueChange={v=>setDelay(v[0])}/><div className="slider-labels mono"><span>0s</span><span>Tunggu halaman termuat</span><span>10s</span></div></div>
 <div className="toggle-row"><label htmlFor="dark-mode">Dark mode <span>Jika didukung website</span></label><div><span className="mono">{dark?'ON':'OFF'}</span><Switch id="dark-mode" checked={dark} onCheckedChange={setDark}/></div></div>
 <details className="advanced"><summary><Plus size={16}/> Kontrol lanjutan <span className="mono">SCALE</span></summary><div><p className="field-help">Scale mengatur resolusi gambar, atau skala layout PDF.</p><Choice label="Scale output" value={String(scale)} onChange={v=>setScale(Number(v))} options={[{value:'0.5',label:'0.5×'},{value:'1',label:'1×'},{value:'1.5',label:'1.5×'},{value:'2',label:'2×'}]}/></div></details>
 <button className="capture-button" type="submit" disabled={engineReady===false}><BrandMark/><span>{busy?'SEDANG CAPTURE…':mode==='batch'?`CAPTURE ${number(selectedCount)} FRAME`:'CAPTURE FRAME'}</span><ArrowUpRight size={23}/></button><p className="capture-footnote" role="status">{engineReady===false?'Mesin capture mandiri belum terhubung.':'Unduh hasil sebelum masa simpannya berakhir.'}</p>
 </fieldset></form><div className="result-side" ref={resultRef} aria-busy={busy}><div className="result-top mono"><span>{result?.mode==='batch'?'CONTACT SHEET':'FRAME'} / {result?.mode==='batch'?String(result.archiveCount).padStart(3,'0'):'001'}</span><span className={`status-label ${state==='error'?'status-error':''}`}>{busy?'MEMPROSES':state==='done'?'CAPTURED':state==='error'?'FRAME LOST':engineReady===false?'MESIN OFFLINE':'SIAP CAPTURE'}<i/></span></div>
 {result?<ResultViewer result={result} onReset={reset}/>:<div className={`empty-frame ${busy?'processing':''} ${state==='error'?'failed-frame':''}`}><CropMarks/>{busy?<><div className="acquisition-mark"><BrandMark/></div><span className="mono">{state==='preparing'?'MENYIAPKAN':state==='finalizing'?'MENYIAPKAN OUTPUT':'MENUNGGU HASIL'}</span><h3>{mode==='batch'?`${urls.length} halaman`:(()=>{try{return new URL(url).hostname;}catch{return 'Website';}})()}</h3><p>Layanan sedang memproses permintaanmu.</p><div className="processing-rail mono"><span>WAKTU BERJALAN</span><span>{elapsed.toFixed(1)} s</span></div><p className="processing-note">Menunggu respons layanan capture.</p><button type="button" className="text-button" onClick={()=>controller.current?.abort()}>Batalkan menunggu <X size={14}/></button></>:state==='error'&&failure?<><span className="failure-code mono">{failure.code}</span><h3>Capture gagal.</h3><p>{failure.message}</p>{failure.row!==undefined&&mode==='batch'&&<span className="mono">PERIKSA URL / {number(failure.row+1)}</span>}<button type="button" className="retry-button" onClick={()=>failure.retryable===false?reset():submit()}>{failure.retryable===false?'UBAH PENGATURAN':'COBA LAGI'} <ArrowUpRight size={18}/></button></>:<><div className="empty-mark"><BrandMark/></div><span className="mono">FRAME / BELUM TERISI</span><h3>Preview Capture</h3><p>Masukkan URL dan tekan Capture <br/>untuk melihat hasilnya.</p><span className="empty-resolution mono">{width} × {height}<span> / </span>{fullPage?'FULL PAGE':'VIEWPORT'}</span></>}</div>}
 <div className="result-bottom mono"><span>JPG · PNG · WEBP · PDF</span><span>{result?'EXPORT READY':'PREVIEW / OUTPUT'}</span></div><p className="sr-only" role="status" aria-live="polite">{busy?'Capture sedang diproses.':failure?failure.message:result?'Capture selesai. Hasil siap diunduh.':''}</p></div></div></section>;
}
