import test from 'node:test';import assert from 'node:assert/strict';
import {readFile,mkdtemp,rm,readdir} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {zipSync} from 'fflate';
import {normalize,parsePublicUrl,publicAddress,validateNetwork} from '../server/capture/validation';
import {parseOutput,MIME} from '../server/capture/parser';
import {toSSWeb,ssweb} from '../server/capture/providers/ssweb';
import {capture} from '../server/capture/service';import {getConfig} from '../server/config';import {nodeStore} from '../server/utils/node-files';import {handle} from '../server/handler';import {CaptureError} from '../server/capture/errors';
import type {CaptureOptions,CaptureProvider} from '../server/capture/model';
import {captureProxy,publicEndpoint} from '../server/utils/capture-proxy';
import {viewportPresets} from '../src/capture/presets';
import sharp from 'sharp';
const config=getConfig();const options:CaptureOptions={mode:'single',targets:['https://example.com/'],viewport:{preset:'desktop',width:800,height:600,fullPage:false,scale:1},appearance:{darkMode:false},output:{format:'jpeg'},timing:{delay:1}};
const bytes=async(format:string)=>new Uint8Array(await readFile(new URL(`./fixtures/frame.${format}`,import.meta.url)));
const fixture:CaptureProvider={async capture(o){if(o.mode==='batch'){const p=await bytes(o.output.format);return{bytes:zipSync({'01-example.png':p,'02-example.png':p}),filename:'screenshots.zip',mimeType:MIME.zip};}return {bytes:await bytes(o.output.format),filename:`example.${o.output.format}`,mimeType:MIME[o.output.format]};}};
test('reject unsafe protocols, credentials, metadata, private IP and integer/hex IP forms',()=>{for(const u of ['file:///etc/passwd','ftp://example.com','http://localhost','http://127.0.0.1','http://2130706433','http://0x7f000001','http://10.0.0.1','http://169.254.169.254','http://[::1]','http://[::ffff:127.0.0.1]','http://user:pass@example.com','http://example.com:8080'])assert.throws(()=>parsePublicUrl(u),CaptureError);assert.equal(parsePublicUrl('https://example.com/#x').href,'https://example.com/');});
test('public IP ranges exclude reserved and private networks',()=>{for(const ip of ['192.168.1.1','100.64.0.1','0.0.0.0','224.0.0.1','fc00::1','fe80::1','2001:db8::1'])assert.equal(publicAddress(ip),false,ip);assert.equal(publicAddress('1.1.1.1'),true);});
test('browser proxy refuses loopback destinations for HTTP and HTTPS',async()=>{
 await assert.rejects(publicEndpoint('127.0.0.1'),/Private destination/);
 const proxy=await captureProxy();
 try{const {request}=await import('node:http');
   for(const target of ['http://127.0.0.1/private','http://169.254.169.254/latest']){
    const status=await new Promise<number>((resolve,reject)=>{const req=request(proxy.url,{path:target,method:'GET'},r=>{r.resume();resolve(r.statusCode||0);});req.on('error',reject);req.end();});
    assert.equal(status,403);
   }
 }finally{await proxy.close();}
});
test('device presets map to supported viewport bounds',()=>{for(const p of viewportPresets){if(!p.width)continue;assert.equal(normalize({...options,viewport:{...options.viewport,preset:p.value,width:p.width,height:p.height}},'single',5).viewport.preset,p.value);}});
test('WEBP encoding produces WEBP binary rather than a renamed PNG',async()=>{
 const webp=await sharp(await bytes('png')).webp({quality:90}).toBuffer();
 assert.equal(webp.toString('ascii',0,4),'RIFF');
 assert.equal(webp.toString('ascii',8,12),'WEBP');
 assert.equal((await sharp(webp).metadata()).format,'webp');
});
test('reject a mixed public/private DNS result before fetch',async()=>{let called=false;await assert.rejects(validateNetwork('https://example.com',AbortSignal.timeout(1000),async()=>['1.1.1.1','10.0.0.1'],(async()=>{called=true;return new Response();}) as typeof fetch),/privat/);assert.equal(called,false);});
test('reject private redirect and redirect loops',async()=>{await assert.rejects(validateNetwork('https://example.com',AbortSignal.timeout(1000),async()=>['1.1.1.1'],(async()=>new Response(null,{status:302,headers:{location:'http://127.0.0.1/admin'}})) as typeof fetch),CaptureError);await assert.rejects(validateNetwork('https://example.com',AbortSignal.timeout(1000),async()=>['1.1.1.1'],(async()=>new Response(null,{status:302,headers:{location:'/loop'}})) as typeof fetch),/pengalihan/);});
test('normalized configuration and exact provider mapping',()=>{const o=normalize({...options,viewport:{...options.viewport,width:1024,height:768,scale:.5,fullPage:true},appearance:{darkMode:true},timing:{delay:8}},'single',5);const p=toSSWeb(o);assert.equal(p.width,1024);assert.equal(p.fullPage,true);assert.equal(p.darkMode,true);assert.equal(p.scale,.5);assert.equal(p.delay,8);assert.equal(p.script,'');assert.throws(()=>normalize({...options,viewport:{...options.viewport,width:1}},'single',5));assert.throws(()=>normalize({...options,targets:Array(6).fill('https://example.com')},'batch',5));});
for(const format of ['jpeg','png','webp','pdf'] as const)test(`single ${format}: Base64 parse → store → preview/download bytes`,async()=>{const root=await mkdtemp(join(tmpdir(),'folio-test-'));try{const b=await bytes(format);const parsed=parseOutput({filename:`example.${format}`,base64:`data:${MIME[format]};base64,${Buffer.from(b).toString('base64')}`},MIME[format],config.maxOutput);assert.deepEqual(parsed.bytes,b);const store=nodeStore(root);const result=await capture({...options,output:{format}},fixture,store,config,AbortSignal.timeout(2000));assert.ok(result.previewUrl);assert.equal('base64' in result,false);const response=await handle(new Request(`http://localhost${result.downloadUrl}`),store,config);assert.equal(response.status,200);assert.match(response.headers.get('content-disposition')!,/attachment/);assert.deepEqual(new Uint8Array(await response.arrayBuffer()),b);}finally{await rm(root,{recursive:true,force:true});}});
test('native image batch produces downloadable ZIP and safe contact-sheet items',async()=>{const root=await mkdtemp(join(tmpdir(),'folio-test-'));try{const result=await capture({...options,mode:'batch',targets:['https://example.com','https://example.org'],output:{format:'png'}},fixture,nodeStore(root),config,AbortSignal.timeout(2000));assert.equal(result.items?.length,2);assert.equal(result.partial,false);assert.equal(result.type,'archive');assert.equal('filepath' in result,false);assert.match(result.downloadUrl,/batch_/);}finally{await rm(root,{recursive:true,force:true});}});
test('unverified PDF request is rejected before provider network access',async()=>{let called=false;const provider=ssweb(config,(async()=>{called=true;return new Response();}) as typeof fetch);await assert.rejects(provider.capture({...options,output:{format:'pdf'}},AbortSignal.timeout(1000)),(e:unknown)=>e instanceof CaptureError&&e.code==='FORMAT_UNAVAILABLE');assert.equal(called,false);});
test('image formats and batch payload preserve verified provider fields',()=>{for(const format of ['jpeg','png','webp'] as const){const single=toSSWeb({...options,output:{format}});assert.equal(single.format,format);assert.equal(single.mimeType,MIME[format]);assert.equal(single.type,'img');assert.deepEqual(single.urls,[{url:null}]);const batch=toSSWeb({...options,mode:'batch',targets:['https://rhmt.biz.id','http://discussion-group.my.id','https://veritas.web.id'],output:{format},viewport:{...options.viewport,width:2048,height:1080},timing:{delay:6}});assert.deepEqual(batch.size,['2048x1080']);assert.equal(batch.url,null);assert.equal(batch.type,'multiple-imgs');assert.equal(batch.delay,'6');assert.equal(batch.mimeType,'');assert.equal(batch.urls.length,3);}});
test('Cloudflare denial is distinct from API registration; redirects stay manual on Workers',async()=>{for(const [body,code] of [[{error_code:1010,cloudflare_error:true},'PROVIDER_ACCESS_DENIED'],[{error:'API access requires registration'},'PROVIDER_AUTH_REQUIRED']] as const){const provider=ssweb(config,(async(_url,init)=>{assert.equal(init?.redirect,'manual');return Response.json(body,{status:403});}) as typeof fetch);await assert.rejects(provider.capture(options,AbortSignal.timeout(1000)),(e:unknown)=>e instanceof CaptureError&&e.code===code);}});
test('batch rejects files whose true format differs from selected output',async()=>{const root=await mkdtemp(join(tmpdir(),'folio-test-'));try{const b=await bytes('png');const provider:CaptureProvider={async capture(){return{bytes:zipSync({'pretend.jpeg':b}),filename:'screenshots.zip',mimeType:MIME.zip};}};await assert.rejects(capture({...options,mode:'batch'},provider,nodeStore(root),config,AbortSignal.timeout(1000)),/Format dalam ZIP/);}finally{await rm(root,{recursive:true,force:true});}});
test('provider access restriction becomes a safe normalized failure',async()=>{const provider=ssweb(config,(async()=>Response.json({success:false,error:'API access requires registration'})) as typeof fetch);await assert.rejects(provider.capture(options,AbortSignal.timeout(1000)),(e:unknown)=>e instanceof CaptureError&&e.code==='PROVIDER_AUTH_REQUIRED');});
test('mismatched format and invalid Base64 are rejected',async()=>{assert.throws(()=>parseOutput({base64:'data:image/png;base64,AAAA'},MIME.png,100));const b=await bytes('png');assert.throws(()=>parseOutput({base64:`data:image/png;base64,${Buffer.from(b).toString('base64')}`},MIME.jpeg,config.maxOutput));});
test('timeout, request size, origin, retry, and rate limiting',async()=>{const root=await mkdtemp(join(tmpdir(),'folio-test-'));const store=nodeStore(root);const request=()=>new Request('http://localhost/api/capture',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(options)});try{const timeout=await handle(request(),store,{...config,timeout:15},'timeout',{validate:async()=>{},provider:{async capture(o,signal){await new Promise((_,reject)=>{signal.addEventListener('abort',()=>reject(signal.reason));setTimeout(()=>reject(new Error('test guard')),50);});throw new Error();}}});assert.equal(timeout.status,504);const deps={validate:async()=>{},provider:fixture};assert.equal((await handle(request(),store,config,'retry',deps)).status,200);assert.equal((await handle(request(),store,{...config,rateLimit:1},'limited',deps)).status,200);assert.equal((await handle(request(),store,{...config,rateLimit:1},'limited',deps)).status,429);const evil=new Request('http://localhost/api/capture',{method:'POST',headers:{'content-type':'application/json',origin:'https://other.test'},body:'{}'});assert.equal((await handle(evil,store,config)).status,403);const large=new Request('http://localhost/api/capture',{method:'POST',headers:{'content-type':'application/json'},body:'a'.repeat(17000)});assert.notEqual((await handle(large,store,config)).status,200);}finally{await rm(root,{recursive:true,force:true});}});
test('expiration prevents reads and cleanup preserves already-open downloads',async()=>{const root=await mkdtemp(join(tmpdir(),'folio-test-'));try{const store=nodeStore(root);const id='cap_'+ 'a'.repeat(32);const b=await bytes('png');await store.put(id,b,{filename:'x.png',mimeType:MIME.png,bytes:b.length,expires:Date.now()+15});const open=await store.get(id);await new Promise(r=>setTimeout(r,25));assert.equal(await store.get(id),null);await store.cleanup();assert.deepEqual(await readdir(join(root,'captures')),[]);assert.deepEqual(new Uint8Array(await new Response(open!.body).arrayBuffer()),b);assert.equal(await store.get('../../etc/passwd'),null);}finally{await rm(root,{recursive:true,force:true});}});
