'use client';
import {Github} from '@/src/brand/SocialIcons';
import {useState} from 'react';
import {ArrowDown,ArrowUpRight,Menu,X} from 'lucide-react';
import {BrandMark} from '@/src/brand/BrandMark';
import {CaptureCore} from '@/src/brand/CaptureCore';
import {CaptureWorkspace} from '@/src/capture/CaptureWorkspace';
import {DeveloperSignature} from '@/src/brand/DeveloperSignature';
export default function Page(){const[menu,setMenu]=useState(false);return <><a className="skip-link" href="#capture">Langsung ke capture</a><header className="header"><a href="#" className="brand" aria-label="FOLIO beranda"><BrandMark/><span>FOLIO<span className="brand-period">.</span></span></a><span className="header-caption mono">WEB CAPTURE INSTRUMENT</span><nav aria-label="Navigasi utama" className={menu?'nav-open':''}><a href="#capture" onClick={()=>setMenu(false)}>Capture <span>↗</span></a><a href="#info" onClick={()=>setMenu(false)}>Tentang</a><a className="github-link" href="https://github.com/rahmat-369" target="_blank" rel="noopener noreferrer" aria-label="GitHub R_hmt ofc"><Github size={19}/></a></nav><button className="mobile-menu" onClick={()=>setMenu(!menu)} aria-label={menu?'Tutup menu':'Buka menu'} aria-expanded={menu}>{menu?<X/>:<Menu/>}</button></header>
 <main><section className="hero"><div className="hero-top mono"><span><span className="signal-square"/>001 / WEB CAPTURE</span><span className="hero-edition">SINGLE / BATCH / EXPORT</span></div><div className="hero-composition"><div className="hero-type"><h1>TANGKAP<br/>WEB.<br/><span>SIMPAN.</span></h1><div className="hero-description"><span className="description-rule"/><p>Screenshot halaman web dalam<br/>JPG, PNG, WEBP, atau PDF.</p></div></div><CaptureCore/><span className="hero-side mono">SCROLL / FRAME / CAPTURE</span></div><div className="hero-bottom"><a className="start-link" href="#capture"><span className="round-arrow"><ArrowDown size={20}/></span>MULAI CAPTURE <span className="mono">[ 01 ]</span></a><div className="hero-formats mono"><span>JPG</span><span>PNG</span><span>WEBP</span><span>PDF</span></div><span className="hero-caption mono">URL → CAPTURE → DOWNLOAD</span></div></section>
 <div className="transition-ruler" aria-hidden="true"><span>0</span><span>480</span><span>960</span><span>1440</span><span>1920 PX</span></div><CaptureWorkspace/>
 <section id="info" className="info-section section-wrap"><div className="info-title"><span className="mono section-index">003 / FITUR CAPTURE</span><h2>PILIH<br/>FORMAT.<br/><span>ATUR<br/>VIEWPORT.</span></h2><p>Screenshot untuk dokumentasi,<br/>referensi desain, atau arsip halaman.</p></div><div className="editorial-rows"><article><span className="mono">01 / OUTPUT</span><h3>Format<br/>output.</h3><p>JPG, PNG, WEBP, atau PDF dari mesin capture mandiri.</p><div className="output-types mono"><span>JPG</span><span>PNG</span><span>WEBP</span><span>PDF</span></div></article><article><span className="mono">02 / BATCH</span><h3>Capture<br/>beberapa URL.</h3><p>Masukkan beberapa URL. Hasilnya terkumpul dalam satu arsip ZIP yang mudah diunduh.</p><span className="editorial-end mono">MULTIPLE FRAMES → ONE ZIP</span></article><article><span className="mono">03 / VIEWPORT</span><h3>Ukuran dan<br/>area capture.</h3><p>Pilih Desktop, Mobile, iPad, MacBook, PC, atau ukuran custom. Capture satu layar atau halaman utuh.</p><span className="editorial-end mono">PRESET / CUSTOM / FULL PAGE</span></article></div></section>
 <section className="how-section section-wrap"><div className="how-heading"><span className="mono section-index">004 / CARA KERJA</span><p>URL → Pengaturan → Download</p></div><div className="steps"><div><span className="step-number mono">01</span><h3>TEMPEL<br/>TAUTAN.</h3><p>Masukkan URL halaman publik.</p></div><div><span className="step-number mono">02</span><h3>ATUR<br/>FRAME.</h3><p>Tentukan format dan area capture.</p></div><div><span className="step-number mono">03</span><h3>CAPTURE.<br/>SIMPAN.</h3><p>Pratinjau hasilnya, lalu unduh.</p></div></div></section>
 <section className="brand-break"><span className="mono">005 / CAPTURE & EXPORT</span><div className="break-composition"><h2>MASUKKAN URL.<br/><span>ATUR OUTPUT.</span><br/>DOWNLOAD.</h2><div className="break-frames" aria-hidden="true"><i/><i/><i/><BrandMark/></div></div><a href="#capture">BUKA CAPTURE <ArrowUpRight size={21}/></a><span className="break-end mono">SINGLE / BATCH / ZIP</span></section>
 <DeveloperSignature/></main><footer><a href="#" className="brand footer-brand"><BrandMark/><span>FOLIO.</span></a><span className="mono">WEB CAPTURE / V1</span><span className="mono">© {new Date().getFullYear()} FOLIO</span><a href="#" aria-label="Kembali ke atas"><ArrowUpRight size={20}/></a></footer></>;}
